apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "docs-site.fullname" . }}-pvc
  labels:
    app: {{ include "docs-site.name" . }}
    chart: {{ include "docs-site.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | default "1Gi" }}
  {{- if .Values.persistentVolume.storageClass }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  {{- end }}
